blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.index),
    path('<int:post_id>', views.detail, name='fullstory'),
]

portfolio/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index),
]

proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls')),
    path('blog/', include('blog.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone

class Post(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    created_at = models.DateTimeField(default=timezone.now)
    photo = models.ImageField(upload_to='blog/images')

    def __str__(self):
        return self.title
        
    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

portfolio/models.py
from django.db import models

# Create your models here.
class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    photo = models.ImageField(upload_to='portfolio/images')
    link = models.URLField(blank=True)

    def __str__(self):
        return self.title
    
    class Meta:
        verbose_name = 'Проект'
        verbose_name_plural = 'Проекты'

blog/views.py
from django.shortcuts import render, get_object_or_404

from .models import Post

# Create your views here.
def index(request):
    posts = Post.objects.order_by('-created_at')
    return render(request, 'blog/index.html', {'posts': posts})

def detail(request, post_id):
    blog = get_object_or_404(Post, pk=post_id)
    return render(request, 'blog/fullstory.html', {'blog': blog})

portfolio/views.py
from django.shortcuts import render

from .models import Project

# Create your views here.

projects = Project.objects.all()

def index(request):
    return render(request, 'portfolio/index.html', context={'projects': projects})

blog/templates/blog/fullstory.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>

    <h1>Fullstory</h1>

    <p>{{ blog.title }}</p>
    <p>{{ blog.content|safe }}</p>

</body>

</html>

blog/templates/blog/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
    <h1>Blog</h1>

    <p>Количество постов: {{ posts.count }}</p>

    {% for item in posts %}
    <a href="{% url 'blog:fullstory' item.pk %}" style="display: block; margin-top: 50px">
        <div><img src="{{ item.photo.url }}" width="300" alt=""></div>
        <div>{{ item.title }}</div>
        <div>{{ item.content|striptags }}</div>
        <div>{{ item.created_at|date:'d E Y H:s' }}</div>
    </a>
    {% endfor %}

</body> 
</html>

portfolio/templates/portfolio/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>

    <h1>Index</h1>

    {% for item in projects %}
        <div><img src="{{ item.photo.url }}" width="300" alt=""></div>
        <div>{{ item.title }}</div>
        <div>{{ item.description }}</div>
    {% endfor %}

</body>

</html>